# The categories of the notes that GitHub generates from the merged pull requests of a release.
changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
      - question
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - '*'
